import { z } from 'zod'
import { inline, finite, empty, array } from './common.js'
const row=z.record(z.string().max(64),z.union([finite,z.string().max(256)]))
const chartInput=z.object({rows:z.array(row).min(1).max(20_000)}).strict()
const chartParameters=z.object({title:z.string().max(200).default('Data chart'),mark:z.enum(['line','point','bar']).default('line'),x:z.string().min(1),y:z.string().min(1),group:z.string().optional()}).strict()
const seriesSchema=z.object({name:z.string(),x:array,y:array,entityIds:z.array(z.string()).optional()}).superRefine((s,ctx)=>{if(s.x.length!==s.y.length || (s.entityIds && s.entityIds.length!==s.x.length))ctx.addIssue({code:'custom',message:'Series lengths must match'})})
export const chart=inline({id:'plot.chart',title:'Analytical chart',description:'Declarative line, point or bar charts over inline data. No remote data or arbitrary Vega expressions.',inputSchema:chartInput,parameterSchema:chartParameters,outputSchema:chartInput,
 execute:(raw,params)=>{const data=chartInput.parse(raw),p=chartParameters.parse(params);for(const r of data.rows)if(!(p.x in r) || typeof r[p.y]!=='number' || (p.group && !(p.group in r)))throw new Error('Missing chart field or nonnumeric y');return{data,views:[{id:'chart',kind:'chart',title:p.title,mark:p.mark,x:p.x,y:p.y,...(p.group === undefined ? {} : {group:p.group}),...data}],artifacts:[{id:'data',name:'chart-data.json',mediaType:'application/json',encoding:'utf8',content:JSON.stringify(data.rows)}]}}})
const scientificInput=z.object({series:z.array(seriesSchema).min(1).max(32)}).strict()
const scientificParams=z.object({title:z.string().default('Scientific plot'),xLabel:z.string().default('x'),yLabel:z.string().default('y')}).strict()
export const scientific=inline({id:'plot.scientific',title:'Scientific plot',description:'Numerical series with linked entity ids; renderer-ready view data and independent JSON export.',inputSchema:scientificInput,parameterSchema:scientificParams,outputSchema:scientificInput,
 execute:(raw,params)=>{const data=scientificInput.parse(raw),p=scientificParams.parse(params);return{data,views:[{id:'plot',kind:'scientific_plot',...p,series:data.series.map(s=>({name:s.name,x:s.x,y:s.y,...(s.entityIds === undefined ? {} : {entityIds:s.entityIds})}))}],artifacts:[{id:'data',name:'series.json',mediaType:'application/json',encoding:'utf8',content:JSON.stringify(data)}]}}})
const surfaceInput=z.object({x:array,y:array,z:z.array(array).min(1).max(256)}).strict().superRefine((s,ctx)=>{if(s.x.length>256 || s.y.length>256 || s.z.length!==s.y.length || s.z.some(row=>row.length!==s.x.length))ctx.addIssue({code:'custom',message:'Surface dimensions must match and be <=256'})})
export const surface=inline({id:'plot.surface',title:'Scientific surface',description:'3D numerical surface from an explicit rectangular grid.',inputSchema:surfaceInput,parameterSchema:empty,outputSchema:surfaceInput,execute:raw=>{const data=surfaceInput.parse(raw);return{data,views:[{id:'surface',kind:'surface',title:'Numerical surface',...data}]}}})
