import { z } from 'zod'
import { meshSchema, vector3Schema } from 'papyrus-rendering'
import { worker, finite, array, expression } from './common.js'
import { circuitSchema } from './circuits.js'
const empty=z.object({}).strict()
export const rasterSchema=z.object({width:z.number().int().min(2).max(1024),height:z.number().int().min(2).max(1024),values:z.array(finite.min(0).max(1)).max(1_048_576)}).strict().refine(r=>r.values.length===r.width*r.height,'Raster dimensions do not match values')
const polygonSchema=z.object({type:z.literal('polygon'),units:z.string(),frame:z.enum(['image','cartesian']),rings:z.array(z.array(z.tuple([finite,finite])).min(4)).min(1)})
const fieldResult=z.object({type:z.literal('timeseries'),time:array,variables:z.array(z.string()),values:z.array(array),units:z.array(z.string())})
const symbolic=z.object({mode:z.literal('symbolic'),expression,variable:z.string().regex(/^[a-zA-Z][a-zA-Z0-9_]*$/),operation:z.enum(['simplify','differentiate','integrate'])}).strict()
const linear=z.object({mode:z.literal('linear'),matrix:z.array(array).min(1).max(256),rhs:array}).strict().refine(s=>s.matrix.length===s.rhs.length && s.matrix.every(r=>r.length===s.rhs.length),'Linear system must be square')
const ode=z.object({mode:z.literal('ode_ivp'),variables:z.array(z.string().regex(/^[a-zA-Z][a-zA-Z0-9_]*$/)).min(1).max(32),derivatives:z.array(expression).min(1).max(32),initial:array,time:z.tuple([finite,finite]),samples:z.number().int().min(2).max(2000).default(201)}).strict().refine(s=>s.time[1]>s.time[0] && s.variables.length===s.derivatives.length && s.initial.length===s.variables.length && new Set(s.variables).size===s.variables.length && !s.variables.includes('t'),'ODE dimensions/time/variables invalid')
const pde=z.object({mode:z.literal('heat_1d'),lengthM:finite.positive(),diffusivity:finite.positive(),initial:array,leftTemperature:finite,rightTemperature:finite,duration:finite.positive(),samples:z.number().int().min(2).max(256).default(51)}).strict().refine(s=>s.initial.length>=3 && s.initial.length<=256,'Heat grid must have 3..256 points')
export const math=worker({id:'math.solve',title:'Mathematical solution',description:'Safe expression AST: symbolic simplify/differentiate/integrate (SymPy), square linear solve, ODE IVP (SciPy), or 1D heat-equation method-of-lines preset. General PDE/BVP solvers are not yet supported.',inputSchema:z.union([symbolic,linear,ode,pde]),parameterSchema:z.object({rtol:finite.min(1e-12).max(0.01).default(1e-7),atol:finite.min(1e-14).max(0.01).default(1e-9)}).strict(),outputSchema:z.union([z.object({type:z.literal('expression'),latex:z.string(),expression:z.string()}),z.object({type:z.literal('solution'),values:array,residual:finite}),fieldResult,z.object({type:z.literal('heat_field'),x:array,time:array,temperatures:z.array(array)})])})
export const vectorize=worker({id:'vision.vectorize',title:'Raster vectorization',description:'Threshold normalized grayscale raster, trace cell boundaries with holes, simplify with Shapely, and export GeoJSON and SVG in image coordinates.',inputSchema:z.object({raster:rasterSchema}).strict(),parameterSchema:z.object({threshold:finite.min(0).max(1).default(0.5),simplifyPx:finite.nonnegative().max(20).default(0)}).strict(),outputSchema:z.object({type:z.literal('multipolygon'),units:z.literal('px'),frame:z.literal('image'),polygons:z.array(polygonSchema),geojson:z.record(z.string(),z.unknown()),areaPx:finite.nonnegative()})})
export const meshProcess=worker({id:'mesh.process',title:'Mesh inspection and processing',description:'Trimesh measurement, cleanup, convex hull or subdivision. Volumes are reported only for watertight meshes.',inputSchema:z.object({mesh:meshSchema}).strict(),parameterSchema:z.object({operation:z.enum(['measure','repair','convex_hull','subdivide']).default('measure')}).strict(),outputSchema:z.object({mesh:meshSchema,area:finite,volume:finite.nullable(),watertight:z.boolean(),bounds:z.array(vector3Schema)})})
export const meshReconstruct=worker({id:'mesh.reconstruct',title:'Image-grid mesh reconstruction',description:'Height-map or calibrated depth-grid reconstruction. Hidden geometry is not recovered from a single photograph.',inputSchema:z.object({raster:rasterSchema}).strict(),parameterSchema:z.discriminatedUnion('mode',[
 z.object({mode:z.literal('height_map'),widthM:finite.positive(),heightM:finite.positive(),heightScaleM:finite.positive()}),
 z.object({mode:z.literal('depth_map'),depthScaleM:finite.positive(),fx:finite.positive(),fy:finite.positive(),cx:finite,cy:finite}),
]),outputSchema:z.object({mesh:meshSchema,source:z.literal('reconstructed'),assumptions:z.array(z.string())})})
export const cad=worker({id:'cad.reconstruct',title:'Constrained CAD reconstruction',description:'Extrude a calibrated vectorized silhouette or explicit polygon into a CadQuery BRep and STEP. Supports disconnected contours and holes; dimensions come from user-provided scale and thickness.',inputSchema:z.union([z.object({polygon:polygonSchema}).strict(),z.object({polygons:z.array(polygonSchema).min(1).max(64)}).strict()]),parameterSchema:z.object({mode:z.literal('silhouette_extrusion').default('silhouette_extrusion'),mmPerUnit:finite.positive(),thicknessMm:finite.positive().max(100_000)}).strict(),outputSchema:z.object({type:z.literal('solid'),units:z.literal('mm'),mesh:meshSchema,volumeMm3:finite.positive(),features:z.array(z.record(z.string(),z.unknown())),assumptions:z.array(z.string())})})
export const sensor=worker({id:'sensor.simulate',title:'Synthetic range sensor',description:'Open3D raycasting of an explicit mesh and ray set. Returns simulated ranges and point cloud with no claim of measured LiDAR.',inputSchema:z.object({mesh:meshSchema,origins:z.array(vector3Schema).min(1).max(20_000),directions:z.array(vector3Schema).min(1).max(20_000)}).strict().refine(r=>r.origins.length===r.directions.length && r.directions.every(d=>Math.hypot(...d)>0),'Ray dimensions must match and directions be nonzero'),parameterSchema:z.object({maxRange:finite.positive().default(1000)}).strict(),outputSchema:z.object({type:z.literal('point_cloud'),source:z.literal('simulated'),units:z.enum(['mm','m','km','normalized']),points:z.array(vector3Schema),ranges:z.array(finite.nullable()),hits:z.number().int().nonnegative()})})
const geometry=z.object({type:z.enum(['Point','MultiPoint','LineString','MultiLineString','Polygon','MultiPolygon']),coordinates:z.unknown()}).strict()
export const geo=worker({id:'geo.compute',title:'Geospatial computation',description:'Shapely buffer, union, intersection, area and PROJ reprojection. Metric operations require a projected CRS; geographic area is rejected.',inputSchema:z.object({geometry,other:geometry.optional(),crs:z.string().max(128)}).strict(),parameterSchema:z.object({operation:z.enum(['buffer','union','intersection','area','reproject']),distance:finite.optional(),targetCrs:z.string().max(128).optional()}).strict(),outputSchema:z.object({geometry:z.record(z.string(),z.unknown()),crs:z.string(),area:finite.nonnegative().nullable(),units:z.string()})})
export const fea=worker({id:'fea.solve',title:'Linear structural FEA',description:'scikit-fem 2D rectangular cantilever, linear isotropic elasticity, SI units, end traction. Reports displacement, force balance and mesh; general imported-geometry FEA is an adapter extension point.',inputSchema:z.object({lengthM:finite.positive(),heightM:finite.positive(),thicknessM:finite.positive(),youngModulusPa:finite.positive(),poissonRatio:finite.min(-0.99).max(0.49),tractionPa:finite}).strict(),parameterSchema:z.object({nx:z.number().int().min(2).max(80).default(24),ny:z.number().int().min(2).max(30).default(8),deformationScale:finite.nonnegative().max(10000).default(100)}).strict(),outputSchema:z.object({mesh:meshSchema,displacement:z.array(vector3Schema),vonMisesPa:array,maxDisplacementM:finite.nonnegative(),relativeResidual:finite.nonnegative(),reactionN:finite})})
export const spice=worker({id:'spice.simulate',title:'SPICE simulation',description:'ngspice passive R/C/DC-source circuits through a generated netlist; operating point, AC sweep or transient. No arbitrary netlists, control blocks, file includes or shell commands.',inputSchema:z.object({circuit:circuitSchema}).strict(),parameterSchema:z.discriminatedUnion('analysis',[
 z.object({analysis:z.literal('op')}),z.object({analysis:z.literal('ac'),startHz:finite.positive(),stopHz:finite.positive(),points:z.number().int().min(2).max(2000).default(101)}).refine(p=>p.stopHz>p.startHz,'AC range invalid'),
 z.object({analysis:z.literal('tran'),stepS:finite.positive(),stopS:finite.positive()}).refine(p=>p.stopS/p.stepS<=20_000 && p.stopS>p.stepS,'Transient range invalid'),
]),outputSchema:z.object({type:z.literal('spice_result'),analysis:z.string(),series:z.array(z.object({name:z.string(),x:z.array(finite),y:z.array(finite)})),converged:z.boolean(),netlist:z.string()})})
export const workerOperators=[math,vectorize,meshProcess,meshReconstruct,cad,sensor,geo,fea,spice]
